### ISSUE TITLE
[caiyun] 有这个签到吗

### ISSUE THREAD

**Issue by TrickYun** [asunajs/asign#19]
![Screenshot_2024-03-21-08-46-07-53_0a71aec8c0e0ef1865eaad406f5276fb.jpg](https://github.com/asunajs/asign/assets/119123314/43a6ea88-5d32-44f7-b35d-08fbcf141434)

**Comment by catlair** [comment]
如果是由地区移动提供的没法做哦，活动页面进不去

**Comment by TrickYun** [comment]
应该是云南的
