### ISSUE TITLE
登录失败，SSOtoken

### ISSUE THREAD

**Issue by cyikns** [asunajs/asign#8]
![image](https://github.com/asunajs/asign/assets/29618492/e0e0aec7-a8da-4736-8dda-d85fcee275e3)
不知道要怎么解决

**Comment by catlair** [comment]
未知异常是移动返回的，他都说未知了，我 emmmmm。

你发一下你的 token 看看，记得把中间删除一部分或者改些字符，防止泄露

**Comment by cyikns** [comment]
![1710390736179](https://github.com/asunajs/asign/assets/29618492/21fd135c-d8a4-4c07-99cb-932053d06570)

**Comment by catlair** [comment]
好的，auth 和 token 反了，（）

**Comment by cyikns** [comment]
谢谢，被自己蠢哭

**Comment by chen360781** [comment]
也是这个问题，获取 ssoToken 失败 输入参数错误，报错这个问题怎么处理
